/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConceptConceptIdRouteRouteImport } from './routes/concept/$conceptId/route'
import { Route as ConceptConceptIdIndexRouteImport } from './routes/concept/$conceptId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptConceptIdRouteRoute = ConceptConceptIdRouteRouteImport.update({
  id: '/concept/$conceptId',
  path: '/concept/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptConceptIdIndexRoute = ConceptConceptIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConceptConceptIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concept/$conceptId': typeof ConceptConceptIdRouteRouteWithChildren
  '/concept/$conceptId/': typeof ConceptConceptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concept/$conceptId': typeof ConceptConceptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concept/$conceptId': typeof ConceptConceptIdRouteRouteWithChildren
  '/concept/$conceptId/': typeof ConceptConceptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/concept/$conceptId' | '/concept/$conceptId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/concept/$conceptId'
  id:
    '__root__' | '/' | '/about' | '/concept/$conceptId' | '/concept/$conceptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConceptConceptIdRouteRoute: typeof ConceptConceptIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$conceptId': {
      id: '/concept/$conceptId'
      path: '/concept/$conceptId'
      fullPath: '/concept/$conceptId'
      preLoaderRoute: typeof ConceptConceptIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$conceptId/': {
      id: '/concept/$conceptId/'
      path: '/'
      fullPath: '/concept/$conceptId/'
      preLoaderRoute: typeof ConceptConceptIdIndexRouteImport
      parentRoute: typeof ConceptConceptIdRouteRoute
    }
  }
}

interface ConceptConceptIdRouteRouteChildren {
  ConceptConceptIdIndexRoute: typeof ConceptConceptIdIndexRoute
}

const ConceptConceptIdRouteRouteChildren: ConceptConceptIdRouteRouteChildren = {
  ConceptConceptIdIndexRoute: ConceptConceptIdIndexRoute,
}

const ConceptConceptIdRouteRouteWithChildren =
  ConceptConceptIdRouteRoute._addFileChildren(
    ConceptConceptIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConceptConceptIdRouteRoute: ConceptConceptIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
